apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-rest
  namespace: supabase
data:
  DB_DRIVER: postgres
  DB_HOST: supabase-db
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_SSL: allow
  PGRST_DB_ANON_ROLE: anon
  PGRST_DB_SCHEMA: public,storage
  PGRST_DB_USE_LEGACY_GUCS: "false"
