apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-meta
  labels:
    workload: supabase-meta
  namespace: supabase
data:
  DB_DRIVER: postgres
  DB_HOST: supabase-db
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_SSL: disable
  PG_META_PORT: "8080"
